# Generated by Django 3.1.5 on 2021-03-06 09:14

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
