# Generated by Django 3.1.5 on 2021-03-07 09:20

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210306_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_location)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(max_length=60),
        ),
    ]
